### ISSUE TITLE
Cohen's kappa

### ISSUE THREAD

**Issue by AnsHovenkamp** [jasp-stats/jaspReliability#182]
Recently I calculated Cohen's kappa with SPSS and with JASP. Unfortunately, JASP sometimes produces strange results that do not correspond at all to the results of SPSS. E.g.: a test with N=59. Cohen's kappa in SPSS is 0.873, and kappa in JASP is -0.031. 
For comparison, I also calculated the percentage agreement: 93.3%. Higher than Cohen's kappa from SPSS, but that is what you expect.
So it seems that de kappa from SPSS is right, but what happens with the kappa from JASP? There were 14 missings, can this be the reason for the result in JASP?

**Comment by shun2wang** [comment]
Hi @AnsHovenkamp we recommed to file a issue at https://github.com/jasp-stats/jasp-issues/issues where you may needs give us more infomation about bugs/request then developer will notice that.

**Comment by EJWagenmakers** [comment]
@juliuspfadt this would be good to check
